2025-01-12 16:36:51,449 INFO    MainThread:22560 [wandb_setup.py:_flush():68] Current SDK version is 0.19.2
2025-01-12 16:36:51,449 INFO    MainThread:22560 [wandb_setup.py:_flush():68] Configure stats pid to 22560
2025-01-12 16:36:51,449 INFO    MainThread:22560 [wandb_setup.py:_flush():68] Loading settings from /Users/jerry/.config/wandb/settings
2025-01-12 16:36:51,449 INFO    MainThread:22560 [wandb_setup.py:_flush():68] Loading settings from /Users/jerry/Project-Build-an-ML-Pipeline-Starter/components/train_val_test_split/wandb/settings
2025-01-12 16:36:51,449 INFO    MainThread:22560 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-12 16:36:51,449 INFO    MainThread:22560 [wandb_init.py:_log_setup():523] Logging user logs to /Users/jerry/Project-Build-an-ML-Pipeline-Starter/components/train_val_test_split/wandb/run-20250112_163651-gjhsc0fo/logs/debug.log
2025-01-12 16:36:51,449 INFO    MainThread:22560 [wandb_init.py:_log_setup():524] Logging internal logs to /Users/jerry/Project-Build-an-ML-Pipeline-Starter/components/train_val_test_split/wandb/run-20250112_163651-gjhsc0fo/logs/debug-internal.log
2025-01-12 16:36:51,450 INFO    MainThread:22560 [wandb_init.py:init():641] calling init triggers
2025-01-12 16:36:51,450 INFO    MainThread:22560 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {}
2025-01-12 16:36:51,450 INFO    MainThread:22560 [wandb_init.py:init():674] starting backend
2025-01-12 16:36:52,083 INFO    MainThread:22560 [wandb_init.py:init():678] sending inform_init request
2025-01-12 16:36:52,134 INFO    MainThread:22560 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-12 16:36:52,134 INFO    MainThread:22560 [wandb_init.py:init():693] backend started and connected
2025-01-12 16:36:52,136 INFO    MainThread:22560 [wandb_init.py:init():786] updated telemetry
2025-01-12 16:36:52,154 INFO    MainThread:22560 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-12 16:36:52,349 ERROR   MainThread:22560 [wandb_init.py:init():845] encountered error: failed to upsert bucket: returned error 400 Bad Request: {"errors":[{"message":"you may not log runs directly to your organization, please try using your team entity","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-01-12 16:36:52,349 ERROR   MainThread:22560 [wandb_init.py:init():1299] error in wandb.init()
Traceback (most recent call last):
  File "/Users/jerry/miniconda3/envs/data_check_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
  File "/Users/jerry/miniconda3/envs/data_check_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 851, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 400 Bad Request: {"errors":[{"message":"you may not log runs directly to your organization, please try using your team entity","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-01-12 16:36:52,354 WARNING MsgRouterThr:22560 [router.py:message_loop():75] message_loop has been closed
